export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED'

export const FETCH_CALENDAR = 'FETCH_CALENDAR'
export const FETCH_CALENDAR_SUCCESS = 'FETCH_CALENDAR_SUCCESS'
export const FETCH_CALENDAR_REJECTED = 'FETCH_CALENDAR_REJECTED'

export const CREATE_EVENT = 'CREATE_EVENT'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_REJECTED = 'CREATE_EVENT_REJECTED'

export const FETCH_EVENTS = 'FETCH_EVENTS'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_REJECTED = 'FETCH_EVENTS_REJECTED'

export const UPDATING_EVENT = 'UPDATING_EVENT'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_REJECTED = 'UPDATE_EVENT_REJECTED'

export const DELETE_EVENT = 'DELETE_EVENT'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_REJECTED = 'DELETE_EVENT_REJECTED'
