export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED'

export const FETCH_CALENDAR = 'FETCH_CALENDAR'
export const FETCH_CALENDAR_SUCCESS = 'FETCH_CALENDAR_SUCCESS'
export const FETCH_CALENDAR_REJECTED = 'FETCH_CALENDAR_REJECTED'

export const CREATE_ACTIVITY = 'CREATE_ACTIVITY'
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS'
export const CREATE_ACTIVITY_REJECTED = 'CREATE_ACTIVITY_REJECTED'

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES'
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS'
export const FETCH_ACTIVITIES_REJECTED = 'FETCH_ACTIVITIES_REJECTED'

export const UPDATING_ACTIVITY = 'UPDATING_ACTIVITY'
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS'
export const UPDATE_ACTIVITY_REJECTED = 'UPDATE_ACTIVITY_REJECTED'

export const DELETE_ACTIVITY = 'DELETE_ACTIVITY'
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS'
export const DELETE_ACTIVITY_REJECTED = 'DELETE_ACTIVITY_REJECTED'
